// Generated by LiveScript 1.6.0
(function(){
  var R, ReactDOM, componentize, DOMImport, noteOffsets, notes, tunings, rxTone, parseTone, formatTone, Fretboard, App, slice$ = [].slice, arrayFrom$ = Array.from || function(x){return slice$.call(x);}, toString$ = {}.toString, this$ = this;
  R = preact;
  ReactDOM = R;
  componentize = function(elem){
    return function(){
      var props, args, arg;
      props = {};
      args = arrayFrom$(arguments);
      while (args.length) {
        arg = args.shift();
        if (toString$.call(arg).slice(8, -1) === 'Object' && !R.isValidElement(arg)) {
          import$(props, arg);
        } else {
          args.unshift(arg);
          break;
        }
      }
      return R.createElement.apply(R, [elem, props].concat(arrayFrom$(args)));
    };
  };
  DOMImport = function(tag){
    return this$[tag] = componentize(tag);
  };
  ['div', 'nav', 'ul', 'ol', 'li', 'p', 'a', 'i', 'b', 'span', 'small', 'sub', 'br', 'h1', 'h2', 'h3', 'table', 'caption', 'thead', 'tbody', 'tfoot', 'tr', 'th', 'td', 'form', 'label', 'input', 'select', 'datalist', 'option', 'button', 'hr', 'img'].forEach(DOMImport);
  noteOffsets = {
    C: 0,
    D: 2,
    E: 4,
    F: 5,
    G: 7,
    A: 9,
    B: 11
  };
  notes = {
    '♯': ['C', 'C♯', 'D', 'D♯', 'E', 'F', 'F♯', 'G', 'G♯', 'A', 'A♯', 'B'],
    '♭': ['C', 'D♭', 'D', 'E♭', 'E', 'F', 'G♭', 'G', 'A♭', 'A', 'B♭', 'B']
  };
  tunings = {
    '': '',
    Banjo: 'G4 D3 G3 B3 D4',
    Bass: 'E1 A1 D2 G2',
    Guitar: 'E2 A2 D3 G3 B3 E4',
    Lute: 'D2 F2 G2 C3 F3 A3 D4 G4',
    Ukulele: 'G4 C4 E4 A4',
    Violin: 'G3 D4 A4 E5'
  };
  rxTone = /([A-G])(?:([#♯])|([b♭]))?([0-9])?/;
  parseTone = function(s){
    var m, note, sharp, flat, octave;
    if (m = rxTone.exec(s.toUpperCase())) {
      s = m[0], note = m[1], sharp = m[2], flat = m[3], octave = m[4];
      return Number(octave || 1) * 12 + noteOffsets[note] + (function(){
        switch (false) {
        case !sharp:
          return 1;
        case !flat:
          return -1;
        default:
          return 0;
        }
      }());
    }
  };
  formatTone = function(tone, naming){
    return [notes[naming][tone % 12], sub(Math.floor(tone / 12))];
  };
  Fretboard = componentize(Fretboard = (function(superclass){
    var prototype = extend$((import$(Fretboard, superclass).displayName = 'Fretboard', Fretboard), superclass).prototype, constructor = Fretboard;
    Fretboard.prototype.state = {};
    Fretboard.prototype.toggleNote = function(note){
      var ref$;
      return this.setState((ref$ = {}, ref$[note] = !this.state[note], ref$));
    };
    Fretboard.prototype.render = function(){
      var strings, col, row, i, j, this$ = this;
      strings = this.props.tuning.split(' ').reverse().map(parseTone).filter((function(it){
        return it !== undefined;
      }));
      col = function(i, j){
        var toneOffset, noteOffset;
        toneOffset = strings[i] + j;
        noteOffset = toneOffset % 12;
        return td({
          key: j,
          className: this$.state[noteOffset] ? 'active c' + noteOffset : void 8,
          onClick: function(){
            return this$.toggleNote(noteOffset);
          }
        }, formatTone(toneOffset, this$.props.naming));
      };
      row = function(i){
        var j;
        return tr({
          key: i
        }, (function(){
          var i$, to$, results$ = [];
          for (i$ = 0, to$ = this.props.nfrets; i$ <= to$; ++i$) {
            j = i$;
            results$.push(col(i, j));
          }
          return results$;
        }.call(this$)));
      };
      return table(tbody((function(){
        var i$, len$, results$ = [];
        for (i$ = 0, len$ = strings.length; i$ < len$; ++i$) {
          i = i$;
          results$.push(row(i));
        }
        return results$;
      }())), tfoot(tr((function(){
        var i$, to$, results$ = [];
        for (i$ = 0, to$ = this.props.nfrets; i$ <= to$; ++i$) {
          j = i$;
          results$.push(td(j));
        }
        return results$;
      }.call(this)))));
    };
    function Fretboard(){
      this.render = bind$(this, 'render', prototype);
      this.toggleNote = bind$(this, 'toggleNote', prototype);
      Fretboard.superclass.apply(this, arguments);
    }
    return Fretboard;
  }(R.Component)));
  App = componentize(App = (function(superclass){
    var prototype = extend$((import$(App, superclass).displayName = 'App', App), superclass).prototype, constructor = App;
    App.prototype.state = {
      naming: '♯',
      tuning: tunings.Guitar,
      nnecks: 12,
      nfrets: 12
    };
    App.prototype.onChangeNaming = function(e){
      return this.setState({
        naming: e.target.value
      });
    };
    App.prototype.onChangeTuning = function(e){
      return this.setState({
        tuning: e.target.value
      });
    };
    App.prototype.onChangeNecks = function(e){
      return this.setState({
        nnecks: Number(e.target.value)
      });
    };
    App.prototype.onChangeFrets = function(e){
      return this.setState({
        nfrets: Number(e.target.value)
      });
    };
    App.prototype.render = function(){
      var radio, k, v, i, this$ = this;
      radio = function(name, value){
        return input({
          type: 'radio',
          name: name,
          value: value
        }, {
          checked: this$.state[name] === value,
          onChange: function(){
            var ref$;
            return this$.setState((ref$ = {}, ref$[name] = value, ref$));
          }
        });
      };
      return div(form(label(radio('naming', '♯'), '♯'), label(radio('naming', '♭'), '♭'), label('Tuning: ', input({
        type: 'search',
        value: this.state.tuning,
        onInput: this.onChangeTuning
      }), select({
        value: this.state.tuning,
        onChange: this.onChangeTuning
      }, (function(){
        var ref$, results$ = [];
        for (k in ref$ = tunings) {
          v = ref$[k];
          results$.push(option({
            key: k,
            value: v
          }, k));
        }
        return results$;
      }()))), label({
        className: 'nnecks'
      }, 'Necks: ', input({
        type: 'number',
        min: 0,
        value: this.state.nnecks,
        onChange: this.onChangeNecks
      })), label({
        className: 'nfrets'
      }, 'Frets: ', input({
        type: 'number',
        min: 0,
        value: this.state.nfrets,
        onChange: this.onChangeFrets
      })), a({
        href: 'https://github.com/orivej/fretchords#usage',
        target: '_blank'
      }, 'Help')), div({
        className: 'fretboards'
      }, (function(){
        var i$, to$, results$ = [];
        for (i$ = 1, to$ = this.state.nnecks; i$ <= to$; ++i$) {
          i = i$;
          results$.push(div({
            key: i,
            className: 'fretboard'
          }, Fretboard(this.state)));
        }
        return results$;
      }.call(this))));
    };
    function App(){
      this.render = bind$(this, 'render', prototype);
      this.onChangeFrets = bind$(this, 'onChangeFrets', prototype);
      this.onChangeNecks = bind$(this, 'onChangeNecks', prototype);
      this.onChangeTuning = bind$(this, 'onChangeTuning', prototype);
      this.onChangeNaming = bind$(this, 'onChangeNaming', prototype);
      App.superclass.apply(this, arguments);
    }
    return App;
  }(R.Component)));
  ReactDOM.render(App(), document.getElementById('main'));
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
  function bind$(obj, key, target){
    return function(){ return (target || obj)[key].apply(obj, arguments) };
  }
  function extend$(sub, sup){
    function fun(){} fun.prototype = (sub.superclass = sup).prototype;
    (sub.prototype = new fun).constructor = sub;
    if (typeof sup.extended == 'function') sup.extended(sub);
    return sub;
  }
}).call(this);

//# sourceMappingURL=index.js.map
